sudo: false

addons:
  apt:
    packages:
      - libgmp-dev

env:
 - STACK_YAML=stack.yaml

cache:
  directories:
    - $HOME/.stack/

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 - mkdir -p ~/.local/bin
 - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.1.2/stack-1.1.2-linux-x86_64.tar.gz | tar -xvz
 - mv stack-1.1.2-linux-x86_64/stack ~/.local/bin
 - export PATH=~/.local/bin:$PATH
 - stack --version
 - stack setup

install:
 - stack install --only-dependencies --no-terminal

script:
 - stack build --test --bench --no-terminal --ghc-options -Werror
