name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  cabal-build:
    strategy:
      matrix:
        ghc-version:
          # GHC 8.2, 8.4: https://github.com/VinylRecords/Vinyl/pull/168
          # - "8.2.2" # new vinyl doesn't support
          # - "8.4.4" # new vinyl broke support
          - "8.6.5"
          - "8.8.4"
          - "8.10.7"
          - "9.0.2"
          - "9.2.4"
          - "9.4.2"
          - "9.6.4"
          - "9.8.2"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v2
      with:
        cabal-version: "3.4"
        ghc-version: ${{ matrix.ghc-version }}
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc-version }}
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all
