name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  cabal-build:
    strategy:
      matrix:
        ghc-version:
          - "8.2.2"
          - "8.4.4"
          - "8.6.5"
          - "8.8.4"
          - "8.10.2"
          - "9.0.1"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        cabal-version: "3.4"
        ghc-version: ${{ matrix.ghc-version }}
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc-version }}
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all
