name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  cabal-build:
    strategy:
      matrix:
        ghc-version:
          - "9.10"
          - "9.12"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        cabal-version: "3.14"
        ghc-version: ${{ matrix.ghc-version }}
    - name: Cache
      id: cache-dot-cabal
      uses: actions/cache@v4
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc-version }}
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all
